TwitHub/Controllers/TweetController.cs
using Microsoft.AspNetCore.Mvc;
using TwitHub.Data.Entities;
using TwitHub.Models;
using Microsoft.AspNetCore.Identity;
using TwitHub.Data.Repositories;
using TwitHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace TwitHub.Controllers
{
    public class TweetController : Controller
    {
        private readonly ITweetHubRepository<Tweet> _tweetRepository;
        private readonly ITweetHubRepository<Favorite> _favoriteRepository;
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<HomeController> _logger;

        public TweetController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager, ITweetHubRepository<Tweet> tweetRepository, ITweetHubRepository<Favorite> favoriteRepository)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _tweetRepository = tweetRepository;
            _favoriteRepository = favoriteRepository;
        }



        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateTweetModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);

                var tweet = new Tweet
                {
                    Text = model.Text,
                    ApplicationUser = user,
                    CreatedBy = user.UserName
                };

                _tweetRepository.Insert(tweet);

                await _dbContext.SaveChangesAsync();

                ViewBag.Result = "Başarılı";

                return RedirectToAction("Index", "Home");
            }
            ViewBag.Result = "Başarılı";
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Favorite(Guid id)
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var tweet = _tweetRepository.GetContentById(id);

            var remember = user.Favorites.FirstOrDefault(x => x.Tweet.Id == tweet.Id);
            if (remember == null)
            {
                var favorite = new Favorite
                {
                    ApplicationUser = user,
                    Tweet = tweet
                };

                _dbContext.Favorites.Add(favorite);

                await _dbContext.SaveChangesAsync();
            }
            else
            {
                _dbContext.Favorites.Remove(remember);
                await _dbContext.SaveChangesAsync();
            }

            return Ok(new
            {
                IsDeleted = remember != null
            });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Retweet(Guid id)
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var tweet = _tweetRepository.GetContentById(id);

            if (user.Id != tweet.ApplicationUser.Id)
            {
                var remember = user.ReTweets.FirstOrDefault(x => x.Tweet.Id == tweet.Id);
                if (remember == null)
                {
                    var retweet = new ReTweet
                    {
                        ApplicationUser = user,
                        Tweet = tweet
                    };

                    _dbContext.ReTweets.Add(retweet);

                    await _dbContext.SaveChangesAsync();
                }
                else
                {
                    _dbContext.ReTweets.Remove(remember);
                    await _dbContext.SaveChangesAsync();
                }

                return Ok(new
                {
                    IsDeleted = remember != null
                });
            }
            return null;
        }

        [Authorize]
        public async Task<IActionResult> Details(Guid id)
        {
            var tweet = await _dbContext.Tweets
                .FirstOrDefaultAsync(x => x.Id == id);
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.userid = currentuser.Id.ToString();

            return View(tweet);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {

            return View(_tweetRepository.GetContentById(id));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(Tweet UpdateTweet)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var tweetalldetails = await _dbContext.Tweets.FirstOrDefaultAsync(x => x.Id == UpdateTweet.Id);

            if (user.Id == tweetalldetails.ApplicationUser.Id)
            {
                tweetalldetails.Text = UpdateTweet.Text;
                tweetalldetails.UpdatedDate = DateTime.Now;
                tweetalldetails.UpdatedBy = user.Id;

                _dbContext.Tweets.Update(tweetalldetails);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "Tweet Düzenleme Başarısız";
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var tweet = _tweetRepository.GetContentById(id);
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);
            if (tweet.ApplicationUser.Id == currentuser.Id)
            {
                _dbContext.Tweets.Remove(tweet);
                var returnhome = await _dbContext.SaveChangesAsync();

                if (returnhome == 1)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Tweet Düzenleme Başarısız";
                    return View();
                }
            }
            else
            {
                ViewBag.Error = "Tweet Düzenleme Başarısız";
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

TwitHub/Views/Shared/_CreateTweetPartial.cshtml
@using TwitHub.Models;
@model CreateTweetModel

<div class="card">
    <div class="row g-0">
        <div class="col-md-2">
            <img src="~/img/twithubmain.png" class="userlistimg">
        </div>
        <div class="col-md-10">
            <form method="post" asp-controller="tweet" asp-action="Create">
                <div class="form-control">
                    <label asp-for="Text">Tweet</label>
                    <textarea asp-for="Text" class="form-control"></textarea>
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>

                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="submit" class="btn btn-dark me-md-2 btn-lg">Tweet</button>
                </div>
            </form>
        </div>
    </div>
</div>

TwitHub/Views/Shared/_DeletePartial.cshtml
@using TwitHub.Data.Entities;
@model Tweet

<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#Delete+@Model.Id">
    Delete
</button>

<!-- Modal -->
<div class="modal fade" id="Delete+@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Tweet Delete</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="text-danger">
                    <div class="card">
                        <div class="row g-0">
                            <div>
                                <div class="card-body">
                                    <h5 class="card-title">@Model.ApplicationUser</h5>
                                    <p class="text-muted">@Model.CreatedDate</p>
                                    <div class="alert alert-secondary" role="alert">
                                        <p class="card-text fs-5 fw-normal font-monospace">@Model.Text</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger btn-delete" data-tweet-id="@Model.Id">
                    Delete <span data-tweet-id="@Model.Id" class="badge badge-light span-delete"></span>
                </button>
            </div>
        </div>
    </div>
</div>

TwitHub/Views/Shared/_EditPartial.cshtml
@using TwitHub.Data.Entities;
@model Tweet

<!-- Button trigger modal -->
<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#Edit+@Model.Id">
    Edit
</button>

<!-- Modal -->
<div class="modal fade" id="Edit+@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Tweet</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-controller="Tweet" asp-action="Edit">
                <div class="card-body">
                    <input type="hidden" asp-for="Id" value=@Model.Id />
                    <input type="hidden" asp-for="ApplicationUser" value="@Model.ApplicationUser" />
                    <div class="form-control">
                        <h5 class="card-title">@Model.ApplicationUser</h5>
                        <p class="text-muted">@Model.CreatedDate</p>
                        <textarea asp-for="Text" class="form-control"></textarea>
                        <span asp-validation-for="Text" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-warning">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>

TwitHub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TwitHub.Data.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TwitHub</title>
    <script type="text/javascript" href="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/BootstrapV5.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TwitHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 ">
            <div class="container-fluid ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TwitHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@User.Identity.Name</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-dark" asp-controller="user" asp-action="RedirectUserPage">Profile</a></li>
                                    <li><a class="dropdown-item text-dark" asp-area="Identity" asp-page="/Account/Manage/Index">Manage Account</a></li>
                                    <li>
                                        <form class="form dropdown-item text-dark" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button type="submit" class="nav-link btn btn-link dropdown-item text-dark">Logout</button>
                                        </form>
                                    </li>

                                </ul>
                            </ul>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TwitHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/BootstrapV5.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TwitHub/Views/Shared/_TweetPartial.cshtml
@using TwitHub.Data.Entities;
@model Tweet

<div class="card">
    <div class="row g-0">
        <div class="col-md-2">
            <img src="~/img/twithubmain.png" class="userlistimg">
        </div>
        <div class="col-md-10">
            <div class="card-body">
                <a class="display: block text-decoration-none " asp-controller="user" asp-action="Index" asp-route-id="@Model.ApplicationUser.Id">
                    <h5 class="card-title text-decoration-none text-dark">@Model.ApplicationUser.UserName</h5>
                </a>
                <p class="text-muted">@Model.CreatedDate</p>

                <div class="alert alert-secondary text-decoration-none" role="alert">
                    <a class="display: block text-decoration-none " asp-controller="tweet" asp-action="details" asp-route-id="@Model.Id">
                        <p class="card-text fs-5 fw-normal font-monospace text-decoration-none text-dark">@Model.Text</p>
                    </a>
                </div>

                <div class="col-md-12">
                    <input type="hidden" asp-for="Id" value="@Model.Id" />
                    @if (Model.ApplicationUser.Id != ViewBag.userid)
                    {
                        <button type="submit" class="btn btn-info btn-retweet" data-tweet-id="@Model.Id">
                            Retweet <span data-tweet-id="@Model.Id" class="badge badge-light span-retweet-count">@Model.ReTweets.Count</span>
                        </button>
                    }

                    <button type="submit" class="btn btn-info btn-favorite" data-tweet-id="@Model.Id">
                        Favorite <span data-tweet-id="@Model.Id" class="badge badge-light span-fav-count">@Model.Favorites.Count</span>
                    </button>

                    <a class="btn btn-info" asp-controller="Tweet" asp-action="Details" asp-route-id="@Model.Id">Details</a>

                    @if (Model.ApplicationUser.Id == ViewBag.userid)
                    {
                        @await Html.PartialAsync("_EditPartial")
                        @await Html.PartialAsync("_DeletePartial")
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<br />

TwitHub/Views/Shared/_UserPageIndexPartial.cshtml
@using TwitHub.Models;
@model UserPageViewModel

<div>
    @await Html.PartialAsync("_UserPagePartial")
</div>

@if (Model.Tweets.Count() > 0)
{
    @foreach (var tweet in Model.Tweets)
    {
        <div class="card">
            <div class="row g-0">
                <div class="col-md-2">
                    <img src="~/img/twithubmain.png" class="userlistimg">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <h5 class="card-title text-decoration-none" asp-controller="user" asp-action="details" asp-route-id="@Model.User.Id">@tweet.ApplicationUser.UserName</h5>
                        <p class="text-muted">@tweet.CreatedDate</p>

                        <div class="alert alert-secondary text-decoration-none" role="alert">
                            <a class="display: block text-decoration-none " asp-controller="tweet" asp-action="details" asp-route-id="@tweet.Id">
                                <p class="card-text fs-5 fw-normal font-monospace text-decoration-none text-dark">@tweet.Text</p>
                            </a>
                        </div>

                        <div class="col-md-12">
                            @if (Model.User.Id != ViewBag.userid)
                            {
                                <button type="submit" class="btn btn-info btn-retweet" data-tweet-id="@tweet.Id">
                                    Retweet <span data-tweet-id="@tweet.Id" class="badge badge-light span-retweet-count">@tweet.ReTweets.Count</span>
                                </button>
                            }

                            <button type="submit" class="btn btn-info btn-favorite" data-tweet-id="@tweet.Id">
                                Favorite <span data-tweet-id="@tweet.Id" class="badge badge-light span-fav-count">@tweet.Favorites.Count</span>
                            </button>

                            <a class="btn btn-info" asp-controller="Tweet" asp-action="Details" asp-route-id="@tweet.Id">Details</a>

                            @if (Model.User.Id == ViewBag.userid)
                            {
                                <a class="btn btn-info" asp-controller="Tweet" asp-action="Edit" asp-route-id="@tweet.Id">Edit</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
    }
}
else
{
    <div class="alert alert-warning" role="alert">Tweet Not Found</div>
}

@section Scripts
    {
    <script type="text/javascript">

        $(".btn-favorite").click(function () {
            var tweetId = $(this).attr("data-tweet-id");

            $.post("/Tweet/Favorite/" + tweetId, function (res) {
                var existingText = $(".span-fav-count[data-tweet-id='" + tweetId + "']").text();
                var newText = res.isDeleted ? parseInt(existingText) - 1 : parseInt(existingText) + 1;

                $(".span-fav-count[data-tweet-id='" + tweetId + "']").text(newText);
            });
        });

        $(".btn-retweet").click(function () {
            var tweetId = $(this).attr("data-tweet-id");

            $.post("/Tweet/Retweet/" + tweetId, function (res) {
                var existingText = $(".span-retweet-count[data-tweet-id='" + tweetId + "']").text();
                var newText = res.isDeleted ? parseInt(existingText) - 1 : parseInt(existingText) + 1;

                $(".span-retweet-count[data-tweet-id='" + tweetId + "']").text(newText);
            });
        });

        $(document).ready(function () {
            $('#data').after('<div id="nav"></div>');
            var rowsShown = 4;
            var rowsTotal = $('#data tbody tr').length;
            var numPages = rowsTotal / rowsShown;
            for (i = 0; i < numPages; i++) {
                var pageNum = i + 1;
                $('#nav').append('<a href="#" rel="' + i + '">' + pageNum + '</a> ');
            }
            $('#data tbody tr').hide();
            $('#data tbody tr').slice(0, rowsShown).show();
            $('#nav a:first').addClass('active');
            $('#nav a').bind('click', function () {

                $('#nav a').removeClass('active');
                $(this).addClass('active');
                var currPage = $(this).attr('rel');
                var startItem = currPage * rowsShown;
                var endItem = startItem + rowsShown;
                $('#data tbody tr').css('opacity', '0.0').hide().slice(startItem, endItem).
                    css('display', 'table-row').animate({ opacity: 1 }, 300);
            });
        });

    </script>
}

TwitHub/Views/Shared/_UserPageNavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TwitHub.Data.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/user/details/">@User.Identity?.Name!</a>
        </li>
    }
</ul>

TwitHub/Views/Shared/_UserPagePartial.cshtml
@using TwitHub.Models;
@model UserPageViewModel

<section class="container d-flex justify-content-center align-items-center">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card">
                    <div class="rounded-top text-white d-flex flex-row" style="background-color: dimgray; height:200px;">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                                 alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                                 style="width: 150px; z-index: 1">

                            @if (Model.User.Id == ViewBag.userid)
                            {
                                <a type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark" style="z-index: 1;"
                               asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                                    Edit profile
                                </a>
                            }
                            else
                            {
                                if (ViewBag.FollowInfo == null)
                                {
                                    <a type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark" style="z-index: 1;"
                               asp-controller="user" asp-action="NewFollow" asp-route-id="@Model.User.Id">
                                        Follow
                                    </a>
                                }
                                else
                                {
                                    <a type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark" style="z-index: 1;"
                               asp-controller="user" asp-action="UnFollow" asp-route-id="@Model.User.Id">
                                        UnFollow
                                    </a>
                                }

                            }

                        </div>

                        <div class="ms-3" style="margin-top: 130px;">
                            <h5>@Model.User.UserName</h5>
                        </div>
                    </div>

                    <div class="p-4 text-black" style="background-color: white;">
                        <div class="col d-flex justify-content-end text-center py-1">
                            <div>
                            </div>
                            <br />
                            <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <br />

        <div class="container">
            <div class="row">
                <div class="justify-content-center align-items-center text-center">
                    <a class="btn btn-dark" asp-controller="User" asp-action="Index" asp-route-id="@Model.User.Id">Tweet</a>
                    <a class="btn btn-dark" asp-controller="User" asp-action="Retweets" asp-route-id="@Model.User.Id">Retweet</a>
                    <a class="btn btn-dark" asp-controller="User" asp-action="Favorites" asp-route-id="@Model.User.Id">Favorite</a>
                    @if (Model.FollowCount > 0)
                    {
                        <a class="btn btn-dark" asp-controller="User" asp-action="Follows" asp-route-id="@Model.User.Id">Follows @Model.FollowCount</a>
                    }
                    else
                    {
                        <a class="btn btn-dark" asp-controller="User" asp-action="Follows" asp-route-id="@Model.User.Id">Follows</a>

                    }
                    @if (Model.FollowerCount > 0)
                    {
                        <a class="btn btn-dark" asp-controller="User" asp-action="Followers" asp-route-id="@Model.User.Id">Followers @Model.FollowerCount</a>
                    }
                    else
                    {
                        <a class="btn btn-dark" asp-controller="User" asp-action="Followers" asp-route-id="@Model.User.Id">Followers</a>

                    }
                </div>
            </div>
        </div>

</section>